# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend application
COPY . .

# Expose the port your Node.js backend runs on
EXPOSE 3001

# Start your Node.js backend
CMD [ "npm", "start" ]
