const EquipmentList = [
	{ equipment: "Assisted", apiCall: "assisted" },
	{ equipment: "Band", apiCall: "band" },
	{ equipment: "Barbell", apiCall: "barbell" },
	{ equipment: "Body Weight", apiCall: "body weight" },
	{ equipment: "Bosu Ball", apiCall: "bosu ball" },
	{ equipment: "Cable", apiCall: "cable" },
	{ equipment: "Dumbbell", apiCall: "dumbbell" },
	{ equipment: "Elliptical Machine", apiCall: "elliptical machine" },
	{ equipment: "Ez Barbell", apiCall: "ez barbell" },
	// Add the additional items here:
	{ equipment: "Hammer", apiCall: "hammer" },
	{ equipment: "Kettlebell", apiCall: "kettlebell" },
	{ equipment: "Leverage Machine", apiCall: "leverage machine" },
	{ equipment: "Medicine Ball", apiCall: "medicine ball" },
	{ equipment: "Olympic Barbell", apiCall: "olympic barbell" },
	{ equipment: "Resistance Band", apiCall: "resistance band" },
	{ equipment: "Roller", apiCall: "roller" },
	{ equipment: "Rope", apiCall: "rope" },
	{ equipment: "Skierg Machine", apiCall: "skierg machine" },
	{ equipment: "Sled Machine", apiCall: "sled machine" },
	{ equipment: "Smith Machine", apiCall: "smith machine" },
	{ equipment: "Stability Ball", apiCall: "stability ball" },
	{ equipment: "Stationary Bike", apiCall: "stationary bike" },
	{ equipment: "Stepmill Machine", apiCall: "stepmill machine" },
	{ equipment: "Tire", apiCall: "tire" },
	{ equipment: "Trap Bar", apiCall: "trap bar" },
	{ equipment: "Upper Body Ergometer", apiCall: "upper body ergometer" },
	{ equipment: "Weighted", apiCall: "weighted" },
	{ equipment: "Wheel Roller", apiCall: "wheel roller" },
];

export default EquipmentList;
